name: Agentic ML Workflow Scheduler (LangGraph)

on:
  schedule:
    - cron: ' */5 * * * * ' # Runs daily at 9 AM UTC
  workflow_dispatch: # Allows manual triggering from the GitHub UI

jobs:
  run_ml_agent:
    runs-on: ubuntu-latest

    # Environment variables available to all steps in this job
    env:
      OLLAMA_HOST: http://localhost:11434

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # ⚠️ IMPORTANT NOTE:
      # This workflow assumes it's running on a self-hosted runner
      # with Ollama already installed and running with the required model (e.g., tinyllama).
      - name: Verify Ollama Setup (Self-Hosted Check)
        run: |
          echo "Verifying Ollama availability at $OLLAMA_HOST"
          curl --fail $OLLAMA_HOST/api/tags || echo "Warning: Ollama may not be reachable."

      - name: Run LangGraph Multi-Agent Automation
        run: python main_langgraph.py
        env:
          AGENT_EMAIL: ${{ secrets.AGENT_EMAIL }}
          AGENT_PASSWORD: ${{ secrets.AGENT_PASSWORD }}
          CLIENT_EMAIL_TARGET: ${{ secrets.CLIENT_EMAIL_TARGET }}
